config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies, only: %i[index show]
  resources :lists, only: %i[new index create] do
    resources :bookmarks, only: %i[new create]
  end
  get 'lists/:id', to: 'lists#show', as: :list
  delete 'lists/:id', to: 'lists#destroy', as: :delete_list
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }, allow_blank: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, :dependent => :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def index
  #   @bookmarks = Bookmark.all
  # end

  # def show
  #   @bookmark = Bookmark.find(params[:id])
  # end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(params_bookmark)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to lists_path()
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def params_bookmark
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to lists_path()
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path(), status: :see_other
  end

  private

  def params_list
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-5">
  <div class="row">
    <% @lists.each do |list| %>
    <div class="list-card col-4"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
      <%= link_to list.name, list_path(list) %>
      <%= link_to list_path(list),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fa-solid fa-circle-xmark"></i>
      <% end %>

      <%= link_to new_list_bookmark_path(list) do %>
      <i class="fa-solid fa-circle-plus"></i>
      <% end %>
    </div>
    <% end %>
  </div>

  <div class="btn btn-primary"><%= link_to "Create a new list", new_list_path() %></div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container">

  <div class="title text-center">
  <h1><%= @list.name %></h1>
  </div>

  <div class="row d-flex">
  <% @list.movies.each do |movie| %>
    <div class="movie-card col-3">
    <img src="https://image.tmdb.org/t/p/original<%=movie.poster_url%>" alt="">
    <h3><%= movie.title %></h3>
    <%= movie.overview %>
    </div>
  <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
<ul>
<li><%= movie.title %></li>
</ul>
<% end %>